const palavras = [
    "abacaxi", "banana", "cachorro", "dado", "elefante", "faca", "gato", "hotel", "igreja", "janela",
    "kiwi", "limão", "macaco", "navio", "óculos", "pato", "queijo", "rato", "sapo", "tatu",
    "uva", "vaca", "xícara", "zebra", "árvore", "bola", "casa", "dente", "escola", "flor",
    "girafa", "homem", "ilha", "jornal", "livro", "mala", "nuvem", "ovo", "peixe", "quadro",
    "rua", "sol", "telefone", "urso", "vento", "xadrez", "yoga", "zoológico", "água", "bicicleta",
    "computador", "dinheiro", "estrela", "futebol", "guitarra", "helicóptero", "internet", "jardim", "ketchup", "laranja",
    "música", "notebook", "oceano", "papel", "queimadura", "relógio", "sapato", "trabalho", "universo", "violão",
    "webcam", "xarope", "iogurte", "zangado", "amigo", "bebê", "carro", "doce", "espelho", "família",
    "garfo", "hospital", "inverno", "juventude", "karatê", "lua", "montanha", "nariz", "olho", "porta",
    "quarto", "rio", "sorriso", "teclado", "umbigo", "vestido", "waffle", "xícara", "yoga", "zumba",
    "açúcar", "batata", "cebola", "dedo", "escada", "fogo", "gelo", "hora", "irmão", "joelho",
    "kiwi", "lápis", "mão", "nadar", "orelha", "perna", "quente", "rosto", "suco", "tinta",
    "unha", "vela", "xarope", "zíper", "amor", "bolo", "café", "dança", "escola", "festa",
    "grito", "herói", "ideia", "joia", "leite", "medo", "noite", "ouro", "praia", "queda",
    "riso", "sono", "tempo", "uva", "vida", "whisky", "xadrez", "zelo", "avião", "barco",
    "caminho", "dúvida", "energia", "frio", "graça", "história", "imagem", "jogo", "lixo", "mundo",
    "nome", "ontem", "paz", "química", "razão", "sede", "terra", "usar", "viajar", "xingar",
    "yoga", "zero", "alma", "branco", "corpo", "dor", "espaço", "fome", "guerra", "hoje",
    "idade", "juiz", "lei", "mar", "nada", "oração", "poder", "querer", "raiva", "saber",
    "triste", "único", "valor", "web", "xeque", "zelo", "arte", "beleza", "ciência", "dança", "amizade", "alegria", "amor", "aprendizado", "aventura", "beleza", "bondade", "brincadeira", "café", "calma",
    "carinho", "casa", "céu", "chuva", "coragem", "criatividade", "cuidado", "dança", "dedicação", "desejo", 
    "diversão", "doce", "educação", "energia", "esperança", "estudo", "família", "felicidade", "festa", "flor", 
    "força", "fraternidade", "futuro", "garra", "gentileza", "gratidão", "harmonia", "honra", "honestidade", 
    "imaginação", "independência", "inspiração", "inteligência", "jogo", "justiça", "liberdade", "luz", "magia", 
    "mar", "memória", "mente", "música", "natureza", "paz", "persistência", "prazer", "respeito", "Vem", 
    "riso", "sabedoria", "saúde", "serenidade", "sonho", "sucesso", "surpresa", "talento", "garrafa", "trabalho", 
    "transformação", "união", "vida", "vitória", "voz", "vontade", "amizade", "amor", "animal", "árvore", "arte", 
    "beleza", "bondade", "brincar", "bolo", "brincar", "bola", "calma", "casa", "cachorro", "céu", "chuva", "comida", 
    "cor", "coração", "coragem", "cuidar", "doce", "dia", "descobrir", "dança", "educar", "energia", "escola", 
    "estudar", "fazer", "feliz", "festa", "flor", "futuro", "gato", "gente", "girar", "gargalhada", "grande", "gentil", 
    "gente", "gosto", "harmonia", "honestidade", "imaginação", "inteligente", "ir", "jardim", "jogar", "jogo", "justiça", 
    "legal", "ler", "luz", "lago", "magia", "mar", "melodia", "nadar", "natureza", "olhar", "ouvir", "paz", "pular", 
    "pintar", "pintar", "pensar", "persistir", "prazer", "plantar", "quebrar", "resolver", "riso", "saber", "sabedoria", 
    "sorrir", "sonho", "sentir", "ser", "tocar", "tranquilidade", "trabalhar", "unir", "ver", "vida", "vitória", "viajar", 
    "voar", "vontade", "amizade", "alegria", "amor", "aprender", "aventura", "abraço", "azul", "abraço", "amarelo", 
    "beleza", "brincar", "cantar", "casa", "calma", "chuva", "correr", "carinho", "contar", "correr", "conhecer", 
    "cuidar", "criar", "dançar", "ensinar", "escutar", "estudar", "festa", "flor", "brincar", "gargalhar", "girar", 
    "gostar", "ajudar", "imaginar", "jogar", "ler", "lutar", "nadar", "ouvir", "plantar", "pintar", "pular", "querer", 
    "rir", "sonhar", "ser", "tocar", "unir", "ver", "voar", "viver", "vencer", "viajar", "valor", "amizade", "alegria", 
    "amor", "aprender", "aventura", "abraço", "azul", "abraço", "amarelo", "beleza", "brincar", "cantar", "casa", "calma", 
    "chuva", "correr", "carinho", "contar", "correr", "conhecer", "cuidar", "criar", "dançar", "ensinar", "escutar", 
    "estudar", "festa", "flor", "brincar", "gargalhar", "girar", "gostar", "ajudar", "imaginar", "jogar", "ler", "lutar", 
    "nadar", "ouvir", "plantar", "pintar", "pular", "querer", "rir", "sonhar", "ser", "tocar", "unir", "Oxi", "Wanderson", "Mateus", "dos", "Santos", "Santana", "TSI", "Windows", "Linux", "Ubuntu", "Mac", "Android", "excel", "word", "powerpoint", "internet", "excel"
];